version: 2.1

commands:
  run-test:
    steps:
      - checkout
      - run: |
          curl -f https://get.pnpm.io/v6.16.js
          node - add --global pnpm@6 && pnpm config set store-dir ~/.pnpm-store
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Installing Dependencies
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
      - run:
          name: Running Tests
          command: pnpm test

jobs:
  node-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - run-test

  node-lts:
    docker:
      - image: circleci/node:lts
    steps:
      - run-test

workflows:
  node-run-tests:
    jobs:
    - node-latest
    - node-lts
  version: 2
